from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional

class ChatRequest(BaseModel):
    session_id: str = Field(..., description="Unique user session or conversation identity.")
    message: str = Field(..., description="Raw text message sent by the user.")
    context: Optional[Dict[str, Any]] = Field(
        default_factory=dict, 
        description="Optional supplementary user location or role context."
    )

class ChatResponse(BaseModel):
    session_id: str
    agent_resolved: str = Field(..., description="The name of the agent which resolved the query.")
    response: str = Field(..., description="Text response generated by the agent.")
    actions_triggered: List[str] = Field(default_factory=list, description="List of automated actions triggered by the query.")

class TranslationRequest(BaseModel):
    text: str = Field(..., description="Raw string content to translate.")
    target_language: str = Field(..., description="The target language (e.g. Spanish, French).")

class TranslationResponse(BaseModel):
    original_text: str
    translated_text: str
    target_language: str

class HealthResponse(BaseModel):
    status: str
    timestamp: str
    services: Dict[str, str]
